In [1]:
!unzip data02.zip

Archive:  data02.zip
  inflating: train.csv
  inflating: submission_sample.csv
  inflating: test.csv

In [142]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

train = pd.read_csv("train.csv")
#대부분 Nan인 데이터 제거
drop_index = train[train.isnull().sum(1) > 40].index
train= train.drop(drop_index)


train_x = train.loc[:, "sido": "ownerChange"]

#결측값 채우기
imp_most_frequent = SimpleImputer(missing_values= np.nan , strategy='most_frequent')
train_x_imp = imp_most_frequent.fit_transform(train_x)
train_imp_df = pd.DataFrame(train_x_imp, columns=train_x.columns)


train_imp_df

          sido  sgg  openDate  ... employee1 employee2 ownerChange
0    choongnam   73  20071228  ...        62        64        same
1     gyeonggi   89  20161228  ...       234         1        same
2      incheon  141  20000814  ...       663       663        same
3    gyeongnam   32  20050901  ...       206       197        same
4    gyeongnam  155  20020501  ...       397       390        same
..         ...  ...       ...  ...       ...       ...         ...
288    jeonnam  178  20050211  ...       193       141        same
289  choongnam  159  20140618  ...        79        79        same
290  gyeongbuk  107  19830705  ...        54        70        same
291   gyeonggi  169  20070101  ...       100        70        same
292      seoul   79  20011017  ...        15        15        same

[293 rows x 56 columns]

In [158]:
drop_index = train_x[train_x.isnull().sum(1) > 0].index
drop_df = train_x.loc[drop_index, :]
drop_df

          sido  sgg  openDate  ...  employee1 employee2  ownerChange
35    gyeonggi  168  20130206  ...       51.0       NaN       change
48       seoul    1  19940425  ...        NaN       NaN          NaN
62       busan   64  20170602  ...       38.0       NaN          NaN
71     jeonbuk   26  19990805  ...       85.0      74.0         same
93   gyeongbuk  114  20070420  ...        NaN       NaN          NaN
193   gyeonggi   12  20121213  ...       15.0      15.0       change
206  gyeongnam   32  20170120  ...        NaN     103.0          NaN
212    jeonnam   33  19990603  ...        NaN       NaN          NaN
230    jeonnam   53  19990309  ...      461.0       NaN         same
242      busan   69  20170420  ...        NaN       NaN          NaN
263    gangwon  100  20020123  ...        NaN       NaN          NaN
285  gyeongbuk  160  19881104  ...        NaN       NaN          NaN
297  choongnam  159  20140618  ...       79.0      79.0         same
298  gyeongbuk  107  19830705  ...        NaN       NaN          NaN
299   gyeonggi  169  20070101  ...      100.0       NaN          NaN
300      seoul   79  20011017  ...       15.0      15.0         same

[16 rows x 56 columns]

In [124]:
import numpy as np
from sklearn.impute import SimpleImputer

imp_most_frequent = SimpleImputer(missing_values= np.nan , strategy='most_frequent')

test = pd.read_csv("test.csv")
test_x = test.loc[:, "sido": "ownerChange"]

test_imp = imp_most_frequent.fit_transform(test_x)
test_imp_df = pd.DataFrame(test_imp, columns=test_x.columns)

test_imp_df

          sido  sgg     openDate  ... employee1 employee2 ownerChange
0      incheon  139  1.99811e+07  ...       693       693        same
1         jeju  149  2.01603e+07  ...       379       371        same
2      jeonnam  103  1.98904e+07  ...       130        42        same
3        busan   71  2.01002e+07  ...       760       760        same
4      jeonbuk   26  2.00406e+07  ...       437       385        same
..         ...  ...          ...  ...       ...       ...         ...
122    jeonnam   33   2.0011e+07  ...       560        42        same
123   gyeonggi   74  2.00105e+07  ...       132       137        same
124   gyeonggi  116  2.00101e+07  ...       130        42        same
125       jeju   76  2.00102e+07  ...       363       343        same
126  choongbuk  163  1.99612e+07  ...       130        42        same

[127 rows x 56 columns]

In [125]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit([" close", "open"])

train_y = train["OC"]
train_y = le.transform(train_y)
train_y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1])

In [126]:
test_imp_df["sido"].unique()

array(['incheon', 'jeju', 'jeonnam', 'busan', 'jeonbuk', 'gyeonggi',
       'gyeongbuk', 'daejeon', 'seoul', 'daegu', 'choongbuk', 'ulsan',
       'gyeongnam', 'choongnam', 'sejong'], dtype=object)

In [127]:
train_imp_df["sido"].unique()

array(['choongnam', 'gyeonggi', 'incheon', 'gyeongnam', 'busan',
       'jeonnam', 'seoul', 'jeonbuk', 'choongbuk', 'ulsan', 'daejeon',
       'daegu', 'gyeongbuk', 'gangwon', 'gwangju', 'sejong'], dtype=object)

In [128]:
label = ["instkind", "ownerChange"]


for i in label :
  train_imp_df[i] = le.fit_transform(train_imp_df[i])
  test_imp_df[i] = le.transform(test_imp_df[i])
  print(le.classes_)

train_imp_df["sido"] = le.fit_transform(train_imp_df["sido"])
print(le.classes_)
le.fit(['busan', 'choongbuk', 'choongnam', 'daegu', 'daejeon', 'gangwon', 'gwangju',
 'gyeongbuk', 'gyeonggi', 'gyeongnam', 'incheon', 'jeonbuk', 'jeonnam', 'sejong', 'seoul', 'ulsan', 'jeju'])
test_imp_df["sido"] = le.transform(test_imp_df["sido"])

test_imp_df

['clinic' 'dental_clinic' 'general_hospital' 'hospital' 'nursing_hospital'
 'traditional_clinic' 'traditional_hospital']
['change' 'same']
['busan' 'choongbuk' 'choongnam' 'daegu' 'daejeon' 'gangwon' 'gwangju'
 'gyeongbuk' 'gyeonggi' 'gyeongnam' 'incheon' 'jeonbuk' 'jeonnam' 'sejong'
 'seoul' 'ulsan']

     sido  sgg     openDate  ... employee1  employee2 ownerChange
0      10  139  1.99811e+07  ...       693        693           1
1      11  149  2.01603e+07  ...       379        371           1
2      13  103  1.98904e+07  ...       130         42           1
3       0   71  2.01002e+07  ...       760        760           1
4      12   26  2.00406e+07  ...       437        385           1
..    ...  ...          ...  ...       ...        ...         ...
122    13   33   2.0011e+07  ...       560         42           1
123     8   74  2.00105e+07  ...       132        137           1
124     8  116  2.00101e+07  ...       130         42           1
125    11   76  2.00102e+07  ...       363        343           1
126     1  163  1.99612e+07  ...       130         42           1

[127 rows x 56 columns]

In [129]:
test_imp_df["employee1"] = test_imp_df["employee1"].str.replace(',', '').astype('int64')
test_imp_df["employee2"] = test_imp_df["employee2"].str.replace(',', '').astype('int64')

test_imp_df

     sido  sgg     openDate  ... employee1  employee2 ownerChange
0      10  139  1.99811e+07  ...       693        693           1
1      11  149  2.01603e+07  ...       379        371           1
2      13  103  1.98904e+07  ...       130         42           1
3       0   71  2.01002e+07  ...       760        760           1
4      12   26  2.00406e+07  ...       437        385           1
..    ...  ...          ...  ...       ...        ...         ...
122    13   33   2.0011e+07  ...       560         42           1
123     8   74  2.00105e+07  ...       132        137           1
124     8  116  2.00101e+07  ...       130         42           1
125    11   76  2.00102e+07  ...       363        343           1
126     1  163  1.99612e+07  ...       130         42           1

[127 rows x 56 columns]

In [130]:
from imblearn.over_sampling import SMOTE, ADASYN
from collections import Counter

sm = SMOTE(random_state=42)
x_res, y_res = sm.fit_resample(train_imp_df, train_y)
print('Resampled dataset shape %s' % Counter(y_res))

Resampled dataset shape Counter({1: 278, 0: 278})

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [131]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_x_std = scaler.fit_transform(train_imp_df, train_y)
test_x_std = scaler.transform(test_imp_df)

test_x_std

array([[ 0.6912813 ,  1.14409354, -0.78583853, ...,  3.7978803 ,
         4.15022793,  0.40906073],
       [ 0.92957003,  1.33953396,  1.24130996, ...,  1.66418027,
         1.79380481,  0.40906073],
       [ 1.40614749,  0.44050803, -1.81192521, ..., -0.02783026,
        -0.6138449 ,  0.40906073],
       ...,
       [ 0.21470384,  0.69458058, -0.45802659, ..., -0.02783026,
        -0.6138449 ,  0.40906073],
       [ 0.92957003, -0.0871811 , -0.45689527, ...,  1.5554567 ,
         1.58889845,  0.40906073],
       [-1.45331727,  1.61315055, -1.01107348, ..., -0.02783026,
        -0.6138449 ,  0.40906073]])

In [132]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

svm = SVC( class_weight = 'balanced', random_state = 1)

param_grid = {'C' : [0.01, 0.1, 1, 10, 100],
              'gamma' : [0.001, 0.01, 0.1, 1],
              'kernel' :('linear', 'rbf')
              }

clf = GridSearchCV(svm, param_grid, cv = 5)
clf.fit(train_x_std, train_y)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight='balanced', coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=1, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'gamma': [0.001, 0.01, 0.1, 1],
                         'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [133]:
clf.best_params_

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}

In [134]:
pred_train = clf.predict(train_x_std)
pred_test = clf.predict(test_x_std)

In [135]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(train_y, pred_train))
print(accuracy_score(train_y, pred_train))

[[ 15   0]
 [  1 277]]
0.9965870307167235

In [136]:
pred_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [137]:
submit = pd.read_csv('submission_sample.csv')
submit

     inst_id  OC
0          2   0
1          5   0
2          6   0
3          8   0
4         10   0
..       ...  ..
122      424   0
123      425   0
124      429   0
125      430   0
126      431   0

[127 rows x 2 columns]

In [85]:
for i in range(len(pred_test)):
  submit['OC'][i] = pred_test[i]

submit['OC'] = submit['OC'].astype(int)

submit.to_csv("submission.csv", index = False, header = True)